# Autogenerated wrapper script for PortMidi_jll for i686-w64-mingw32
export libportmidi

JLLWrappers.@generate_wrapper_header("PortMidi")
JLLWrappers.@declare_library_product(libportmidi, "libportmidi.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libportmidi,
        "bin\\libportmidi.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
