# Autogenerated wrapper script for PortMidi_jll for x86_64-apple-darwin
export libportmidi

JLLWrappers.@generate_wrapper_header("PortMidi")
JLLWrappers.@declare_library_product(libportmidi, "@rpath/libportmidi.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libportmidi,
        "lib/libportmidi.2.0.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
